// src/vue/CleBottomBar.vue
<template>
  <footer class="cle-fixed-bottombar">
    <div class="cle-footer-inner">
      <slot>
        <span>{{ managedBy }}</span>
        <a
          v-for="link in links"
          :key="`${link.label}-${link.href}`"
          :href="link.href"
          :target="link.newTab ? '_blank' : undefined"
          :rel="link.external ? 'noreferrer' : undefined"
        >
          {{ link.label }}
        </a>
      </slot>
    </div>
  </footer>
</template>

<script setup lang="ts">
import type { CleLink } from "../tokens";

withDefaults(defineProps<{
  managedBy?: string;
  links?: CleLink[];
}>(), {
  managedBy: "Managed by BISS Institute.",
  links: () => [],
});
</script>

// src/svelte/CleBottomBar.svelte
<script lang="ts">
  import type { CleLink } from "../tokens";

  export let managedBy = "Managed by BISS Institute.";
  export let links: CleLink[] = [];
</script>

<footer class="cle-fixed-bottombar">
  <div class="cle-footer-inner">
    <slot>
      <span>{managedBy}</span>
      {#each links as link}
        <a href={link.href} target={link.newTab ? "_blank" : undefined} rel={link.external ? "noreferrer" : undefined}>
          {link.label}
        </a>
      {/each}
    </slot>
  </div>
</footer>
