// src/vue/CleConfirmDialog.vue
<script setup lang="ts">
import CleButton from "./CleButton.vue";
import CleModal from "./CleModal.vue";

withDefaults(defineProps<{
  title: string;
  confirmLabel?: string;
  cancelLabel?: string;
  tone?: "danger" | "primary";
  busy?: boolean;
}>(), {
  confirmLabel: "Confirm",
  cancelLabel: "Cancel",
  tone: "danger",
  busy: false,
});

const open = defineModel<boolean>({ default: false });
const emit = defineEmits<{ confirm: [] }>();
</script>

<template>
  <CleModal v-model="open" :title="title" size="sm" :busy="busy">
    <slot />
    <template #footer>
      <CleButton variant="secondary" data-cle-autofocus :disabled="busy" @click="open = false">
        {{ cancelLabel }}
      </CleButton>
      <CleButton :variant="tone === 'danger' ? 'danger' : 'primary'" :disabled="busy" @click="emit('confirm')">
        {{ busy ? "Working..." : confirmLabel }}
      </CleButton>
    </template>
  </CleModal>
</template>

// src/svelte/CleConfirmDialog.svelte
<script lang="ts">
  import { createEventDispatcher } from "svelte";
  import CleButton from "./CleButton.svelte";
  import CleModal from "./CleModal.svelte";

  export let title: string;
  export let confirmLabel = "Confirm";
  export let cancelLabel = "Cancel";
  export let tone: "danger" | "primary" = "danger";
  export let busy = false;
  export let open = false;

  const dispatch = createEventDispatcher<{ confirm: void }>();
</script>

<CleModal bind:open {title} size="sm" {busy} footer={true}>
  <slot />
  <svelte:fragment slot="footer">
    <CleButton variant="secondary" data-cle-autofocus disabled={busy} on:click={() => (open = false)}>
      {cancelLabel}
    </CleButton>
    <CleButton variant={tone === "danger" ? "danger" : "primary"} disabled={busy} on:click={() => dispatch("confirm")}>
      {busy ? "Working..." : confirmLabel}
    </CleButton>
  </svelte:fragment>
</CleModal>
