// src/vue/CleEmptyState.vue
<script setup lang="ts">
defineProps<{
  title?: string;
  copy?: string;
}>();
</script>

<template>
  <div class="cle-empty-state">
    <div>
      <p v-if="title" class="cle-empty-title">{{ title }}</p>
      <p v-if="copy" class="cle-empty-copy">{{ copy }}</p>
      <slot />
    </div>
  </div>
</template>

// src/svelte/CleEmptyState.svelte
<script lang="ts">
  import type { Snippet } from "svelte";

  let {
    title,
    copy,
    children,
  }: {
    title?: string;
    copy?: string;
    children?: Snippet;
  } = $props();
</script>

<div class="cle-empty-state">
  <div>
    {#if title}<p class="cle-empty-title">{title}</p>{/if}
    {#if copy}<p class="cle-empty-copy">{copy}</p>{/if}
    {#if children}{@render children()}{/if}
  </div>
</div>
