// src/vue/CleKpiCard.vue
<script setup lang="ts">
defineProps<{
  label: string;
  value: string | number;
  note?: string;
}>();
</script>

<template>
  <article class="cle-card cle-kpi-card">
    <div class="cle-kpi-label">{{ label }}</div>
    <div class="cle-kpi-value">{{ value }}</div>
    <div v-if="note" class="cle-kpi-note">{{ note }}</div>
  </article>
</template>

// src/svelte/CleKpiCard.svelte
<script lang="ts">
  let {
    label,
    value,
    note,
  }: {
    label: string;
    value: string | number;
    note?: string;
  } = $props();
</script>

<article class="cle-card cle-kpi-card">
  <div class="cle-kpi-label">{label}</div>
  <div class="cle-kpi-value">{value}</div>
  {#if note}<div class="cle-kpi-note">{note}</div>{/if}
</article>
