// src/vue/CleNavSection.vue
<script setup lang="ts">
defineProps<{
  heading?: string;
  empty?: string;
}>();
</script>

<template>
  <nav class="cle-nav-section" :aria-label="heading">
    <div v-if="heading" class="cle-nav-heading">
      <span>{{ heading }}</span>
      <slot name="action" />
    </div>
    <slot />
    <p v-if="empty" class="cle-nav-empty">{{ empty }}</p>
  </nav>
</template>

// src/svelte/CleNavSection.svelte
<script lang="ts">
  export let heading: string | undefined = undefined;
  export let empty: string | undefined = undefined;
</script>

<nav class="cle-nav-section" aria-label={heading}>
  {#if heading}
    <div class="cle-nav-heading">
      <span>{heading}</span>
      <slot name="action" />
    </div>
  {/if}
  <slot />
  {#if empty}
    <p class="cle-nav-empty">{empty}</p>
  {/if}
</nav>
