// src/svelte/CleButton.svelte
<script lang="ts">
  export let href: string | undefined = undefined;
  export let variant: "primary" | "secondary" = "primary";
  export let type: "button" | "submit" | "reset" = "button";
  export let disabled = false;

  $: className = variant === "secondary" ? "cle-button cle-button-secondary" : "cle-button";
</script>

{#if href}
  <a class={className} {href} aria-disabled={disabled} {...$$restProps}>
    <slot />
  </a>
{:else}
  <button class={className} {type} {disabled} {...$$restProps}>
    <slot />
  </button>
{/if}

// src/vue/CleButton.vue
<template>
  <a v-if="href" :class="classes" :href="href" :aria-disabled="disabled">
    <slot />
  </a>
  <button v-else :class="classes" :type="type" :disabled="disabled">
    <slot />
  </button>
</template>

<script setup lang="ts">
import { computed } from "vue";

const props = withDefaults(defineProps<{
  href?: string;
  variant?: "primary" | "secondary";
  type?: "button" | "submit" | "reset";
  disabled?: boolean;
}>(), {
  variant: "primary",
  type: "button",
  disabled: false,
});

const classes = computed(() => props.variant === "secondary" ? "cle-button cle-button-secondary" : "cle-button");
</script>
