// src/svelte/CleConsoleLayout.svelte
<script lang="ts">
  /**
   * The console arrangement: top bar, sidebar, breadcrumbs, page heading,
   * tabs, content — and the signed-in account pinned to the foot of the
   * sidebar.
   *
   * `CleAppShell` provides the chrome and `CleConsoleHeader` the heading, but
   * every console that used them had to assemble the two the same way and get
   * the same details right: where the account goes, that breadcrumbs sit above
   * the title, that tabs belong under it rather than in the bar. That assembly
   * is the thing worth owning here, so a second console does not have to
   * rediscover it.
   *
   * Omit the `nav` slot and the sidebar disappears, at which point the account
   * falls back to the top bar — a full-width page still has to say who is
   * signed in.
   */
  import type { CleServiceIconName } from "../icons";
  import type { CleLink } from "../tokens";
  import type { CleConsoleUser, CleCrumb } from "../types";
  import CleAppShell from "./CleAppShell.svelte";
  import CleConsoleHeader from "./CleConsoleHeader.svelte";
  import CleServiceIcon from "./CleServiceIcon.svelte";
  import CleSidebarUser from "./CleSidebarUser.svelte";

  export let brand = "Case Law Explorer";
  export let mark = "CLE";
  export let icon: CleServiceIconName | undefined = undefined;
  export let iconLabel: string | undefined = undefined;
  export let favicon = true;
  export let href = "/";
  export let topLinks: CleLink[] = [];
  /** Heading. Omit to render content with no header at all. */
  export let title: string | undefined = undefined;
  export let subtitle: string | undefined = undefined;
  export let crumbs: CleCrumb[] = [];
  export let user: CleConsoleUser | undefined = undefined;
  /** Render the sign-out control in the account block. */
  export let signOut = false;
  export let signOutLabel = "Sign out";
  export let confirmSignOut = true;
  export let signOutTitle = "Sign out?";
  export let signOutCopy: string | undefined = undefined;
  export let busy = false;

  $: hasSidebar = Boolean($$slots.nav || $$slots["nav-footer"]);
  $: showHeader = Boolean(title || crumbs.length || $$slots.actions);
</script>

<!-- A wrapper always forwards its slots, so the shell cannot infer whether a
     sidebar exists from slot presence — it is told. -->
<CleAppShell
  {brand}
  {mark}
  {icon}
  {iconLabel}
  {favicon}
  {href}
  {topLinks}
  sidebar={hasSidebar}
  sidebarFooter={hasSidebar && Boolean(user || signOut || $$slots["user-actions"])}
>
  <svelte:fragment slot="icon">
    {#if $$slots.icon}
      <slot name="icon" />
    {:else}
      <CleServiceIcon {icon} {mark} label={iconLabel} />
    {/if}
  </svelte:fragment>

  <svelte:fragment slot="topbar-actions">
    <!-- Only when there is no sidebar to put it in. -->
    {#if user && !hasSidebar}
      <span class="cle-topbar-account">{user.email || user.name}</span>
    {/if}
    <slot name="topbar-actions" />
    {#if !hasSidebar}
      <slot name="user-actions" />
    {/if}
  </svelte:fragment>

  <svelte:fragment slot="sidebar">
    <slot name="nav" />
    <slot name="nav-footer" />
  </svelte:fragment>

  <svelte:fragment slot="sidebar-footer">
    {#if user}
      <CleSidebarUser name={user.name} email={user.email} initials={user.initials}>
        <svelte:fragment slot="actions"><slot name="user-actions" /></svelte:fragment>
      </CleSidebarUser>
    {:else}
      <div class="cle-sidebar-user-actions"><slot name="user-actions" /></div>
    {/if}
  </svelte:fragment>

  {#if showHeader}
    <CleConsoleHeader title={title || ""} {subtitle} {crumbs} actions={Boolean($$slots.actions)}>
      <svelte:fragment slot="actions"><slot name="actions" /></svelte:fragment>
      <slot name="tabs" />
    </CleConsoleHeader>
  {/if}

  <slot />
</CleAppShell>

// src/vue/CleConsoleLayout.vue
<script setup lang="ts">
/**
 * The console arrangement: top bar, sidebar, breadcrumbs, page heading, tabs,
 * content — and the signed-in account pinned to the foot of the sidebar.
 *
 * `CleAppShell` provides the chrome and `CleConsoleHeader` the heading, but
 * every console that used them had to assemble the two the same way and get
 * the same details right: where the account goes, that breadcrumbs sit above
 * the title, that tabs belong under it rather than in the bar. That assembly
 * is the thing worth owning here, so a second console does not have to
 * rediscover it.
 *
 *     <CleConsoleLayout
 *       brand="Caselaw Access" icon="access"
 *       :crumbs="[{ label: 'Projects', href: '/' }, { label: slug }]"
 *       title="Database Workbench"
 *       :user="{ name: 'dwicker', email: 'dwicker@example.org' }"
 *     >
 *       <template #nav>…</template>
 *       <template #user-actions><button>Sign out</button></template>
 *       <template #tabs>…</template>
 *       …page content
 *     </CleConsoleLayout>
 *
 * Omit `nav` and the sidebar disappears, at which point the account falls back
 * to the top bar — a full-width page still has to say who is signed in.
 */
import { computed, useSlots } from "vue";
import type { CleServiceIconName } from "../icons";
import type { CleLink } from "../tokens";
import type { CleConsoleUser, CleCrumb } from "../types";
import CleAppShell from "./CleAppShell.vue";
import CleConsoleHeader from "./CleConsoleHeader.vue";
import CleSidebarUser from "./CleSidebarUser.vue";

const props = withDefaults(defineProps<{
  brand?: string;
  mark?: string;
  icon?: CleServiceIconName;
  iconLabel?: string;
  favicon?: boolean;
  href?: string;
  topLinks?: CleLink[];
  /** Heading. Omit to render content with no header at all. */
  title?: string;
  subtitle?: string;
  crumbs?: CleCrumb[];
  user?: CleConsoleUser;
  /** Render the sign-out control in the account block. */
  signOut?: boolean;
  signOutLabel?: string;
  confirmSignOut?: boolean;
  signOutTitle?: string;
  signOutCopy?: string;
  busy?: boolean;
}>(), {
  signOut: false,
  brand: "Case Law Explorer",
  mark: "CLE",
  favicon: true,
  href: "/",
  topLinks: () => [],
});

const emit = defineEmits<{ signOut: [] }>();
const slots = useSlots();
const hasSidebar = computed(() => Boolean(slots.nav || slots["nav-footer"]));
const showHeader = computed(() => Boolean(props.title || props.crumbs?.length || slots.actions));
</script>

<template>
  <CleAppShell
    :brand="brand"
    :mark="mark"
    :icon="icon"
    :icon-label="iconLabel"
    :favicon="favicon"
    :href="href"
    :top-links="topLinks"
  >
    <template v-if="$slots.icon" #icon><slot name="icon" /></template>

    <template #topbar-actions>
      <!-- Only when there is no sidebar to put it in. -->
      <span v-if="user && !hasSidebar" class="cle-topbar-account">{{ user.email || user.name }}</span>
      <slot name="topbar-actions" />
      <slot v-if="!hasSidebar" name="user-actions" />
    </template>

    <template v-if="hasSidebar" #sidebar>
      <slot name="nav" />
      <slot name="nav-footer" />
    </template>

    <template v-if="hasSidebar && (user || signOut || $slots['user-actions'])" #sidebar-footer>
      <CleSidebarUser
        v-if="user"
        v-bind="user"
        :sign-out="signOut"
        :sign-out-label="signOutLabel"
        :confirm-sign-out="confirmSignOut"
        :sign-out-title="signOutTitle"
        :sign-out-copy="signOutCopy"
        :busy="busy"
        @sign-out="emit('signOut')"
      >
        <template v-if="$slots['user-actions']" #actions><slot name="user-actions" /></template>
      </CleSidebarUser>
      <div v-else class="cle-sidebar-user-actions"><slot name="user-actions" /></div>
    </template>

    <CleConsoleHeader
      v-if="showHeader"
      :title="title || ''"
      :subtitle="subtitle"
      :crumbs="crumbs"
    >
      <template v-if="$slots.actions" #actions><slot name="actions" /></template>
      <slot name="tabs" />
    </CleConsoleHeader>

    <slot />
  </CleAppShell>
</template>
