// src/svelte/CleGridShell.svelte
<script lang="ts">
  import type { CleLink } from "../tokens";
  import CleBottomBar from "./CleBottomBar.svelte";
  import CleTopBar from "./CleTopBar.svelte";

  export let brand = "Case Law Explorer";
  export let mark = "CLE";
  export let href = "/";
  export let topLinks: CleLink[] = [];
  export let footerText = "Managed by BISS Institute.";
  export let footerLinks: CleLink[] = [];
</script>

<div class="cle-grid-shell">
  <CleTopBar {brand} {mark} {href} links={topLinks} />
  <main class="cle-page">
    <slot />
  </main>
  <CleBottomBar managedBy={footerText} links={footerLinks} />
</div>

// src/vue/CleGridShell.vue
<template>
  <div class="cle-grid-shell">
    <CleTopBar :brand="brand" :mark="mark" :href="href" :links="topLinks" />
    <main class="cle-page">
      <slot />
    </main>
    <CleBottomBar :managed-by="footerText" :links="footerLinks" />
  </div>
</template>

<script setup lang="ts">
import type { CleLink } from "../tokens";
import CleBottomBar from "./CleBottomBar.vue";
import CleTopBar from "./CleTopBar.vue";

withDefaults(defineProps<{
  brand?: string;
  mark?: string;
  href?: string;
  topLinks?: CleLink[];
  footerText?: string;
  footerLinks?: CleLink[];
}>(), {
  brand: "Case Law Explorer",
  mark: "CLE",
  href: "/",
  topLinks: () => [],
  footerText: "Managed by BISS Institute.",
  footerLinks: () => [],
});
</script>
