// src/svelte/CleHero.svelte
<script lang="ts">
  /**
   * The centred hero every Case Law Explorer entry page opens with.
   * Mirrors the Vue component; both take their sizes from the shared tokens,
   * which is what keeps the products agreeing on how big a landing title is.
   */
  import CleHeroPill from "./CleHeroPill.svelte";

  export let eyebrow: string = "";
  export let title: string;
  export let subtitle: string = "";
  export let pills: string[] = [];
  export let align: "center" | "start" = "center";
</script>

<header class="cle-hero cle-hero-{align}">
  {#if pills.length || $$slots.pills}
    <div class="cle-hero-pills">
      {#each pills as pill (pill)}
        <CleHeroPill>{pill}</CleHeroPill>
      {/each}
      <slot name="pills" />
    </div>
  {/if}

  {#if eyebrow}<p class="cle-eyebrow">{eyebrow}</p>{/if}
  <h1 class="cle-hero-title">{title}</h1>
  {#if subtitle}<p class="cle-hero-subtitle">{subtitle}</p>{/if}

  {#if $$slots.actions}
    <div class="cle-hero-actions"><slot name="actions" /></div>
  {/if}

  <slot />
</header>

// src/vue/CleHero.vue
<script setup lang="ts">
/**
 * The centred hero every Case Law Explorer entry page opens with.
 *
 * Each product had drawn its own — same intent, slightly different type scale
 * every time — so arriving from one to another felt like leaving the product.
 * The sizes come from the shared `--cle-text-h1` and `--cle-text-lead` tokens,
 * which is what makes them agree.
 *
 * `align="start"` exists for pages that sit inside a console shell, where a
 * centred title would fight the left-aligned content under it.
 */
import CleHeroPill from "./CleHeroPill.vue";

withDefaults(
  defineProps<{
    eyebrow?: string;
    title: string;
    subtitle?: string;
    /** Short labels above the title — what this product covers, at a glance. */
    pills?: string[];
    align?: "center" | "start";
  }>(),
  { align: "center" },
);
</script>

<template>
  <header class="cle-hero" :class="`cle-hero-${align}`">
    <div v-if="pills?.length || $slots.pills" class="cle-hero-pills">
      <CleHeroPill v-for="pill in pills" :key="pill">{{ pill }}</CleHeroPill>
      <slot name="pills" />
    </div>

    <p v-if="eyebrow" class="cle-eyebrow">{{ eyebrow }}</p>
    <h1 class="cle-hero-title">{{ title }}</h1>
    <p v-if="subtitle" class="cle-hero-subtitle">{{ subtitle }}</p>

    <div v-if="$slots.actions" class="cle-hero-actions">
      <slot name="actions" />
    </div>

    <slot />
  </header>
</template>
