// src/svelte/CleTopBar.svelte
<script lang="ts">
  import type { CleServiceIconName } from "../icons";
  import type { CleLink } from "../tokens";
  import CleServiceIcon from "./CleServiceIcon.svelte";

  export let brand = "Case Law Explorer";
  export let mark = "CLE";
  export let icon: CleServiceIconName | undefined = undefined;
  export let iconLabel: string | undefined = undefined;
  export let href = "/";
  export let links: CleLink[] = [];
</script>

<header class="cle-fixed-topbar">
  <div class="cle-bar-inner">
    <a class="cle-brand" {href} aria-label={brand}>
      <slot name="icon">
        <CleServiceIcon {icon} {mark} label={iconLabel} />
      </slot>
      <span class="cle-brand-text">{brand}</span>
    </a>
    <div class="cle-topbar-right">
      {#if links.length}
        <nav class="cle-link-row" aria-label="Primary">
          {#each links as link}
            <a href={link.href} target={link.newTab ? "_blank" : undefined} rel={link.external ? "noreferrer" : undefined}>
              {link.label}
            </a>
          {/each}
        </nav>
      {/if}
      <div class="cle-topbar-actions">
        <slot name="actions" />
        <slot />
      </div>
    </div>
  </div>
</header>

// src/vue/CleTopBar.vue
<template>
  <header class="cle-fixed-topbar">
    <div class="cle-bar-inner">
      <a class="cle-brand" :href="href" :aria-label="brand">
        <slot name="icon">
          <CleServiceIcon :icon="icon" :mark="mark" :label="iconLabel" />
        </slot>
        <span class="cle-brand-text">{{ brand }}</span>
      </a>
      <div class="cle-topbar-right">
        <nav v-if="links.length" class="cle-link-row" aria-label="Primary">
          <a
            v-for="link in links"
            :key="`${link.label}-${link.href}`"
            :href="link.href"
            :target="link.newTab ? '_blank' : undefined"
            :rel="link.external ? 'noreferrer' : undefined"
          >
            {{ link.label }}
          </a>
        </nav>
        <div class="cle-topbar-actions">
          <slot name="actions" />
          <slot />
        </div>
      </div>
    </div>
  </header>
</template>

<script setup lang="ts">
import type { CleServiceIconName } from "../icons";
import type { CleLink } from "../tokens";
import CleServiceIcon from "./CleServiceIcon.vue";

withDefaults(defineProps<{
  brand?: string;
  mark?: string;
  icon?: CleServiceIconName;
  iconLabel?: string;
  href?: string;
  links?: CleLink[];
}>(), {
  brand: "Case Law Explorer",
  mark: "CLE",
  href: "/",
  links: () => [],
});
</script>
